Repository SDUOJ/sduoj-judger, pull requests merged in 2020-11, with the labels that each got.

#18 refactor, polish, and adapt sduoj-server
  sduoj-judger-interface/pom.xml
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/dto/CommandExecuteResult.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/dto/OneJudgeResult.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/sender/RabbitSender.java
Labels: refactor

#19 refactor submissionHandler
  config.yaml.template
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/enums/JudgeStatus.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/dto/SandboxResultDTO.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/enums/SandboxResult.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/JudgerApplication.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/PathConfig.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AdvancedSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/SPJSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/SubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/listener/SubmissionListener.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/manager/LocalZipManager.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/manager/SubmissionHandlerManager.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/ProcessUtils.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/SandboxRunner.java
  sduoj-judger-service/src/main/resources/bootstrap.yml
Labels: enhancement, refactor

#20 Dockerfile
  Dockerfile
  mavenSettings.xml
  sources.list
Labels: enhancement

#21 Bugfix: consume message repeatly
  Dockerfile
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/enums/SandboxArgument.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/FeignClientErrorDecoder.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AdvancedSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/listener/SubmissionListener.java
Labels: bug, refactor

#22 cpu time first; update README
  README.md
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/enums/SandboxResult.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AdvancedSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
Labels: bug, documentation, refactor

#23 bugfix: display real time in TLE/MLE/RE
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
Labels: bug

#24 bugfix: remove output size limit
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
Labels: bug

#26 delete workspace before initializing workspace; catch OOM
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/ProcessUtils.java
Labels: enhancement

#28 Send final result message with status code, usedTime, judgeScore and usedMemory
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
Labels: enhancement

#29 ci cache repair
  .github/workflows/ci.yml
Labels: bug

#30 adapt Special Judge
  Dockerfile
  docker/mavenSettings.xml
  docker/sources.list
  docker/testlib.h
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AdvancedSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/SPJSubmissionHandler.java
Labels: enhancement

#33 binding CPU affinity in docker parameters
  Dockerfile
  README.md
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/JudgerApplication.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/command/CommandExecutor.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/CpuConfig.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AdvancedSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/SPJSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/SandboxRunner.java
  sduoj-judger-service/src/main/resources/bootstrap.yml
Labels: enhancement

#34 throw SE if no checkpoint
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/SPJSubmissionHandler.java
Labels: bug

#35 update license
  Dockerfile
  LICENSE
  README.md
  docker/testlib
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/dto/BaseDTO.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/dto/CommandExecuteResult.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/dto/UserDTO.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/exception/CompileErrorException.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/exception/SystemErrorException.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/util/NoNullFieldStringStyle.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/dto/Argument.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/dto/SandboxResultDTO.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/enums/SandboxArgument.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/enums/SandboxError.java
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/sandbox/enums/SandboxResult.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/JudgerApplication.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/client/CheckpointClient.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/client/FilesysClient.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/client/JudgeTemplateClient.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/client/ProblemClient.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/client/SubmissionClient.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/command/Command.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/command/CommandExecutor.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/CpuConfig.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/FeignClientErrorDecoder.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/PathConfig.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/RabbitListenerConfig.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/RabbitPublisherConfig.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AbstractSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/AdvancedSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/IOSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/handler/SPJSubmissionHandler.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/listener/SubmissionListener.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/manager/LocalCheckpointManager.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/manager/LocalZipManager.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/manager/SubmissionHandlerManager.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/property/JudgerProperty.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/sender/RabbitSender.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/FileUtils.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/ProcessUtils.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/SandboxRunner.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/util/SpringContextUtils.java
Labels: documentation

#36 add docker-compose-wait in Dockerfile
  Dockerfile
Labels: enhancement
