Repository SDUOJ/sduoj-judger, pull requests merged in 2020-10, with the labels that each got.

#1 adapte the new API.
  README.md
  config.yaml.template
  judger/model/client.py
  judger/model/handler.py
  judger/server.py
Labels: bug

#5 remove sending mq message in client
  judger/model/client.py
Labels: bugfix

#10 localCheckpointManager
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/config/PathConfig.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/listener/SubmissionListener.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/manager/LocalCheckpointManager.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/manager/SubmissionHandlerManager.java
Labels: enhancement

#11 command executor
  sduoj-judger-interface/src/main/java/cn/edu/sdu/qd/oj/judger/dto/CommandExecuteResult.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/command/Command.java
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/command/CommandExecutor.java
  sduoj-judger-service/src/main/resources/bootstrap.yml
Labels: enhancement

#13 bugfix: cannot get callable<V> object from FutureTask wrapper
  sduoj-judger-service/src/main/java/cn/edu/sdu/qd/oj/judger/command/CommandExecutor.java
  sduoj-judger-service/src/main/resources/bootstrap.yml
Labels: bug
